### ISSUE TITLE
Commisioning laser cutter

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#40]
There are a few things left to do before we start cutting for everyone:

- [x] Buy Q-tips (for lens cleaning)
- [x] Buy CO2 fire extinguisher, issue #43
- [x] Install and mount compressor, issue #44
- [x] Find out name and where to get the air duct part for the back side (includes measuring dimensions), issue #51
- [x] Mount tubes closer to the ceiling (check laser door clearance)
- [x] Buy exhaust air tube, issue #45
- [x] Build acrylic window with cutout and adapter for exhaust air tube
- [x] Install new window glass

I think it makes sense to create separate issues for the more difficult tasks and reference them here. Feel free to start with that.

**Comment by emka** [comment]
We started a cut for #41 today. There were too many flames for my taste, before cutting anyting else we must mount the compressor. According to the manual the connector is on the back.

**Comment by emka** [comment]
We got Q-tips and Patrick ordered a longer tube for the compressor.

**Comment by LukasFreeze** [comment]
regarding the back exhausts: "Flachkanal" should be a good keyword, a quick search at Hornbach yielded [promising results](http://www.hornbach.de/shop/Umlenkstueck-Rotheigner-weiss-111x54-mm/8610773/artikel.html) but I don't have the right measurements of course ;-)
The cameo expert suggested foam fittings and a minimum distance to the rear wall of about 10 cm (main casing to wall, tubes can touch). We may have to alter or replace the metal tube fittings in the back to really save space, but that will be difficult!

**Comment by emka** [comment]
We cut a piece of exhaust hood filter and put it above the lamellar filter to avoid damage by small pieces that were sucked in.

**Comment by Pakue95** [comment]
The exhaust canals are finished as far as connecting to the laser is concerned. Only the connection from the door to the filter and filter to window have to be installed. Will likely be done by next week.

**Comment by emka** [comment]
Did you finish the window part today?

**Comment by LukasFreeze** [comment]
Yes, didn't get around to checking all issues tonight - sorry ;-)
